name: odontogram
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  async: ^2.11.0
  camera: ^0.10.5+5
  cloud_firestore: ^4.13.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  exif: ^3.1.4
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  image: ^4.0.17
  image_picker: ^1.0.0
  intl: ^0.17.0
  path_provider: ^2.0.15
  provider: ^6.1.1
  quiver: ^3.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  uses-material-design: true
